spring:

  flyway:
    enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:${DB_SVERO_URL}
    username: ${DB_USER_NAME}
    password: ${DB_PASS}

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

jwt:
  secret: laveronica-siscontrol-jwt-secret-key-2024-muy-seguro-para-produccion
  expiration-ms: 86400000